[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
