set -a terminal-features "tmux-256color:RGB"
set -g prefix C-a
set -g base-index 1
set -g status-position bottom
set -g status-justify right
set -g renumber-windows on
set -g status-style "bg=default"
set -g status-left "#S"
set -g status-right ""
set -g window-status-current-style "fg=green bold"
set -g mode-keys vi
set -s escape-time 0
set -g mouse on
set -g history-limit 100000
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding


bind C-o display-popup -E "tms"
bind E show-environment -g
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'sainnhe/tmux-fzf'
# set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
#Ressurect sessions
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

#Intialize TMUX plugin manager (keep this at end of the conf)
run '~/.tmux/plugins/tpm/tpm'


