set -a terminal-features "tmux-256color:RGB"
set -g prefix C-a
set -g base-index 1
set -g status-position bottom
set -g status-justify right
set -g renumber-windows on
set -g status-style "bg=default"
set -g status-left "#S"
set -g status-right ""
set -g window-status-current-style "fg=green bold"
set -g mode-keys vi
set -s escape-time 0
# Bindings

bind E show-environment -g

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-yank'

# Ressurrect Tmux sessions after reboot (tmux-continuum)
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
